In [2]:
import numpy as np

In [3]:
x = np.array([[-3, -2, 1, -1, 1], 
              [-1, -4, 0, -1.2, 0.9], 
              [-2, -2, 1, -0.8, 1.1], 
              [3, 1, 3, -2, -2]])

w = np.array([[-0.465, 0.911], 
              [-0.146, 0.392], 
              [0.806, 0.522],
              [-0.245, -0.792],
              [0.757, -0.246]])

v = np.matmul(x, w)
v

array([[ 3.495 , -2.449 ],
       [ 2.0243, -1.75  ],
       [ 3.0567, -1.721 ],
       [-0.147 ,  6.767 ]])

In [4]:
def softmax(z):
    assert len(z.shape) == 2
    s = np.max(z, axis=1)
    s = s[:, np.newaxis] # necessary step to do broadcasting
    e_x = np.exp(z - s)
    div = np.sum(e_x, axis=1)
    div = div[:, np.newaxis] # dito
    return e_x / div

softmax(v)

array([[9.97385332e-01, 2.61466815e-03],
       [9.77561874e-01, 2.24381265e-02],
       [9.91654895e-01, 8.34510516e-03],
       [9.92788129e-04, 9.99007212e-01]])

In [27]:
learning_rate = 0.25

def sigmoid(s):
    return 1 / (1 + np.exp(-s))

x = np.array([0.5, 0.7])
u = np.array([[1, -1], [1, -1]])
f1 = np.matmul(x, u)
f1_hat = sigmoid(f1)
w = np.array([-0.5, 0.5])
f2 = np.matmul(f1_hat, w)
y_hat = sigmoid(f2)
y = 1

L = ((y - y_hat) ** 2) / 2

dw = -learning_rate * (y_hat - y) * sigmoid(f2) * (1 - sigmoid(f2)) * f1_hat

w_plus = np.add(w, dw)

du = -learning_rate * (y_hat - y) * (y_hat * (1 - y_hat)) * w * f1_hat * (1 - f1_hat) * x

u_plus = u + du

u_plus

array([[ 0.99845277, -0.99783388],
       [ 0.99845277, -0.99783388]])